// Generated by https://quicktype.io

export interface FetchJob {
  commit: Commit;
  coverage: null;
  allow_failure: boolean;
  created_at: string;
  started_at: string;
  finished_at: string;
  duration: number;
  queued_duration: number;
  artifacts_expire_at: string;
  tag_list: string[];
  id: number;
  name: string;
  pipeline: Pipeline;
  ref: string;
  artifacts: any[];
  runner: null;
  stage: string;
  status: string;
  tag: boolean;
  web_url: string;
  user: User;
}

export interface Commit {
  author_email: string;
  author_name: string;
  created_at: string;
  id: string;
  message: string;
  short_id: string;
  title: string;
}

export interface Pipeline {
  id: number;
  project_id: number;
  ref: string;
  sha: string;
  status: string;
}

export interface User {
  id: number;
  name: string;
  username: string;
  state: string;
  avatar_url: string;
  web_url: string;
  created_at: string;
  bio: null;
  location: null;
  public_email: string;
  skype: string;
  linkedin: string;
  twitter: string;
  website_url: string;
  organization: string;
}
